### ISSUE TITLE
Unable to load RobotModel

### ISSUE THREAD

**Issue by akikohaku** [fkie/fkie_husky_manipulation_simulation#1]
I tried to run this code on ubuntu 20.04.5 with ros noetic and gazebo 11.11 .
All robot nodes in RViz are error and show "No transform from [panda_hand] to [world]".

I got the following error :

```
[Err] [Model.cc:123] Error Code 23 Msg: FrameAttachedToGraph error, Non-LINK vertex with name [__model__] is disconnected; it should have 1 outgoing edge in MODEL attached_to graph.
[Err] [Model.cc:123] Error Code 23 Msg: Graph with __model__ scope has sink vertex named [__model__] when starting from vertex with name [__model__], which is not permitted.
```

and

```
[ERROR] [1668529954.882822426, 22554.300000000]: Action client not connected: effort_joint_trajectory_controller/follow_joint_trajectory
```

**Comment by mnksnz** [comment]
@akikohaku Please let me know if this fixes your issue so that I can close it.

**Comment by akikohaku** [comment]
Thanks, this fixed the problem.

But after the BehaviorTreeCppV3 updated. I failed to build the code. It seems like the namespace has been changed. BehaviorTreeCppV3 needs to be install manually. The correct version of it is v3.7.1.

Here is the method to fix it.
```
git clone https://github.com/BehaviorTree/BehaviorTree.CPP.git
git checkout origin/v3.8
git reset --hard a5411c9
mkdir build
cd build
cmake ..
make
sudo make install
```
